### ISSUE TITLE
Element detail modal improvements

### ISSUE THREAD

**Issue by lorenzoPrimi** [teambtcmap/btcmap-ios#11]
- [ ]  Finish adding rows to match Android. For sure Instagram and Pouch, need to verify what else
- [x]  Phone number parsing isn't working for all formats. Can mimic Android repo implementation
- [ ]  Hide tags initially. Tags button shows/hides.
- [x]  Change "Verify" button to "Verify or Report" to match android

**Comment by salvatoto** [comment]
@lorenzoPrimi 

1. "Finish adding rows to match Android. For sure Instagram and Pouch, need to verify what else"
^ This goes along with the missing contact buttons on the Community Detail screen. Just missing contact links here as well

2. This you fixed

3. Android has the tags dump hidden initially and you can turn them on in Settings. I just implemented on by default. I do like on by default after implementing better styling. We could implement a settings switch to turn off (would require starting a Settings screen first!)

4. Still says just "Verify", Android says "Verify or Report"

**Comment by lorenzoPrimi** [comment]
For the 4, it is a quick fix, but you might want to have a look at https://github.com/teambtcmap/btcmap-ios/issues/6 to keep in sync iOS and android

**Comment by lorenzoPrimi** [comment]
Working on this, I have a question about (1)
Why does the "Verify" button, changes into "Pay" when there is a Pouch link?
There is no need to verify anymore?
Is this the right logic?

**Comment by salvatoto** [comment]
> Why does the "Verify" button, changes into "Pay" when there is a Pouch link? #21

Honestly I don't know. Just saw that on the android app recently. But missed the conversation on it
