### ISSUE TITLE
Different elements shown in community page

### ISSUE THREAD

**Issue by lorenzoPrimi** [teambtcmap/btcmap-ios#28]
The number of elements shown on the community page is different between iOS and Android
Possible causes:
1. They're calling the Areas route with different query params to filter server side 
2. They're filtering app side

EDIT: the correct values are the ones on Android (Ex: 12 in Malaga)
xRef: https://github.com/teambtcmap/btcmap-api/wiki/5.-Areas
https://api.btcmap.org/v2/areas/m%C3%A1laga-2140

Examples:

<img src="https://user-images.githubusercontent.com/1616097/227119644-07dd0daa-aea2-4edd-bf1f-bb93db141810.PNG" width="350">      <img src="https://user-images.githubusercontent.com/1616097/227119650-86db2211-a8c7-4e92-bdd0-c2840ff5bfeb.jpg" width="350">

<img src="https://user-images.githubusercontent.com/1616097/227119700-6e8ad3f9-82bb-4a2c-91f0-fc44d4d3b0b7.PNG" width="350">      <img src="https://user-images.githubusercontent.com/1616097/227119692-cc697812-12b6-41c7-9eb2-d1ce8f4f61a7.jpg" width="350">

<img src="https://user-images.githubusercontent.com/1616097/227119745-87693c7b-bf65-460e-a230-9f1072b9fc44.PNG" width="350">      <img src="https://user-images.githubusercontent.com/1616097/227119738-7ce4f95e-0cc8-4681-9d3d-4d9551fa0564.jpg" width="350">

<img src="https://user-images.githubusercontent.com/1616097/227119777-467f1395-b21c-433b-b12c-e2a33fd4d732.PNG" width="350">      <img src="https://user-images.githubusercontent.com/1616097/227119775-cee6ef9c-0534-45cb-b1e2-e4a08d94fc12.jpg" width="350">

**Comment by salvatoto** [comment]
Fix in f5ca7cdffe22ae245d7f47e15c4c19d581dd5020
