### ISSUE TITLE
Change Community button on main screen from Bitcoin logo to People Hugging emoji icon

### ISSUE THREAD

**Issue by salvatoto** [teambtcmap/btcmap-ios#33]
The Bitcoin logo used to go to Donation page, but right before v1.1 I quickly routed it to the Communities page, because that was more important. But I didn't have time to change the icon. 

Should change to something more appropriate. I vote for the People Hugging emoji that's popular on Nostr

**Comment by tarunsamanta2k20** [comment]
I'd like to work on it.

**Comment by salvatoto** [comment]
@tarunsamanta2k20 Great!

**Comment by salvatoto** [comment]
@tarunsamanta2k20 You have the project cloned, BTCMap.xcodeproj open, but can't run the project on device nor simulator?

Also, you can join the Discord for the project and find me in the "development" channel under "salvanakamoto". DM me there if you want. Discord is listed at bottom of home page: https://btcmap.org/

**Comment by lorenzoPrimi** [comment]
This has been done
