### ISSUE TITLE
Add 'Navigate to' button on Merchant pop-up.

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-ios#59]
The user should be taken to their chosen map app navigation screen with the merchant location as the destination.

**Comment by salvatoto** [comment]
This was implemented by @lorenzoPrimi in commit 03bdbd82dd116ea8d8cfc04fb89f7e5df0e27f9b. If the merchant has an address it's linked to a modal for Apple or Google maps.

https://cdn.discordapp.com/attachments/1119600240731885700/1170714035923210380/IMG_9617.png?ex=655a0b68&is=65479668&hm=8b60edbbfc863c3900a1c6f0b5bcabc2b02dc83caad3bfc770dc7a58407bb892&

https://cdn.discordapp.com/attachments/1119600240731885700/1170715303378964560/IMG_9619.png?ex=655a0c97&is=65479797&hm=4b17bba2dc6ed25b8d1eaf8078250e4cafda4f6a1731ea66b3fc469110ad4f12&
