### ISSUE TITLE
iOS Crash on Launch

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-ios#68]
Multiple reports of app crashing on launch. I have reproduced this myself.

Hunch there has been a change in the API that is causing an unhandled exception.

https://github.com/teambtcmap/btcmap-ios/assets/87125117/7ddabda3-07bc-4789-be45-8d90f25e0b6d

**Comment by salvatoto** [comment]
Fixed: https://github.com/teambtcmap/btcmap-ios/pull/69
